### ISSUE TITLE
ÜbereinstimmungeninBinärdatei: Ganzzahliger Ausdruck erwartet

### ISSUE THREAD

**Issue by chris-aeviator** [FlatheadV8/Postbank_PDF2CSV#1]
Hallo und danke für das Projekt. Ich versuche PB Businesskontoauszüge PDF->CSV umzuwandeln. Ein paar Zeilen werden gelesen, dann erhalte ich einen Fehler (auch in der CSV Datei geschrieben)

```
Zeile 210: ÜbereinstimmungeninBinärdatei(StandardEingabe): Ganzzahliger Ausdruck erwartet
```

Ich denke, es wird hier vielleicht ein Bild geparsed? Wenn ich das Debugging aktiviere (echo von B_ZIFFERN & VON_DATUM) kann ich 5 erfolgreiche Zeilen von Werten sehen bis der Fehler auftritt `B_ZIFFERN='ÜbereinstimmungeninBinärdatei(Standardeingabe)'`

**Comment by FlatheadV8** [comment]
Hallo,
ich denke auch, dass hier versucht wird eine Binärdatei zu lesen.
Das Skript sollte am besten mit eindeutigen Parametern aufgerufen werden.
Ich habe aus Zeitgründen auf einer derartige Überprüfung im Skript verzichtet.

Ich wende es wie folgt an:
cd /Pfad/zu/den/Kontoauszuegen/2019/
/home/bin/postbank_pdf2csv.sh *.pdf

Dann funktioniert es bei mir problemlos, allerdings habe ich gerade noch einen kleineren Fehler gefunden und behoben.
Ich muss auch noch dazu sagen, dass ich keinen Zugang zu "PB Businesskontoauszügen" habe, deshalb weiß ich nicht ob es da Unterschiede zu einem PDF von einem Privatkonto gibt.
Weiterhin ist diese Umwandlung keine reine Wissenschaft, sondern eher ein Hack... :-)
Da kann ich mich immer nur durch Try-and-Error rantasten.

Solltest Du weiterhin Probleme haben, dann geh bitte in das Skript und deaktiviere ganz unten im Skript die Zeile 272 ("rm -f ${NEUERNAME}.txt"), so dass er die Text-Datei nicht löscht.
Starte es dann nocheinmal mit dem problematischen PDF.
Dann sollte dort eine TXT-Datei liegen.
Öffne sie mit einem Editor und tausche alle relevanten persönlchen Daten aus (Ziffern gegen Ziffern und Buchstaben gegen Buchstaben - Groß-Kleinschreibnung bitte nicht ändern).
Diese Datei benötige ich dann zum debuggen.
Anders geht es dann leider nicht.

Gruß

**Comment by hawkeye80** [comment]
Hallo,

ich bin bei der Konvertierung von ein paar Kontoauszügen von diesem Jahr auch auf den Fehler gestoßen. Allerdings habe ich kein Buisness, sondern ein Privat Giro Plus Konto. ES scheint also für beide zu gelten.

Ein paar Neuerungen am PDF hab ich schon ausgemacht und entfernt. [diff_new_postbank_pdf_format.txt](https://github.com/FlatheadV8/Postbank_PDF2CSV/files/5720703/diff_new_postbank_pdf_format.txt)

Interessant ist, dass er bei mir scheinbar alle Buchungen durchparsted. Im CSV ist jedenfalls die letzte Position aus dem PDF noch drin.
Dann folgt ";2020--Binaryfile(standardinput)matches;2020--;;Binary file (standard input) matches;"
Mit dem Parsing der Beträge gibt es aktuell wohl auch ein Problem. Im CSV Fehlen diese, im Debug ist BETRAG auch leer.
Ich würde gerne die an ${NEUERNAME}.txt wie beschrieben Teilen - an welche Adresse darf ich dir die schicken?

Viele Grüße


-- EDIT --
Hab das Problem ausgemacht. Das "Herzchen-Zeichen" was du zur Kapselung der Beträge einfügst erzeugte das Problem. Ich hab es nun gegen ein ¶ (PILCROW SIGN) getauscht und sowohl die Beträge sind im CSV, als auch der Binary Fehler taucht nicht mehr auf.

**Comment by FlatheadV8** [comment]
> 
> -- EDIT --
> Hab das Problem ausgemacht. Das "Herzchen-Zeichen" was du zur Kapselung der Beträge einfügst erzeugte das Problem. Ich hab es nun gegen ein ¶ (PILCROW SIGN) getauscht und sowohl die Beträge sind im CSV, als auch der Binary Fehler taucht nicht mehr auf.

Das finde ich genial! :-)
Prima! Gute Arbeit!

Du kannst mir gerne die korrigierte Datei (im ganzen) zuschicken -> tmp-mail@gmx.net

Viele Grüße und Schöne Weihnachgtstage!
