### ISSUE TITLE
Ghostscript Unrecoverable error // pstotext // KAZ bis 06.2017

### ISSUE THREAD

**Issue by bscholtes** [FlatheadV8/Postbank_PDF2CSV#2]
Hi,

pstotext scheint nicht mehr mit der aktuellen gs Version zu funktionieren.
https://gist.github.com/bscholtes/39a26cd64f5cbd5f6a299a7087bea79e

Direkte Verwendung von
- gs -sDEVICE=txtwrite -dSAFER -q -o PB_KAZ_06-01-2017.txt PB_KAZ_06-01-2017.ps
- ps2txt PB_KAZ_06-01-2017.ps PB_KAZ_06-01-2017.txt (wrapper auf gs)

ist OK, aber dann funzt das KAZ parsing nicht mehr im postbank_pdf2csv_bis_2017-06.sh.
Die ASCII Ausgabe scheint nicht mehr zu passen zum sed Meisterwerk ;-)

Ich habe das ganze unter Ubuntu 20.04 WSL2 mit gs 9.50 und unter CENTOS8 mit gs 9.25 versucht.
https://bugs.launchpad.net/ubuntu/+source/pstotext/+bug/1762778

Worin unterscheidet sich der output von pstotext und ps2txt ...
Irgendwelche Tipps damit das sed parsing mit ps2txt funzt ?

**Comment by bscholtes** [comment]
Mit gs v9.20
- wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs920/ghostscript-9.20.tar.gz
- configure/make
funzt das ganze ...

**Comment by FlatheadV8** [comment]
Ich maintaine die Skripte eigentlich nicht mehr, daher werde ich für diesen Issue keine Anpassungen vornehmen, aber wenigstens klappt es ja mit gs v9.20
