### ISSUE TITLE
RegExp for "ZEILE_4" doesn't match thousands separator '.'

### ISSUE THREAD

**Issue by dukeofnukem815** [FlatheadV8/Postbank_PDF2CSV#6]
The RegExp for "ZEILE_4" (page header) doesn't match thousands separator '.'

Symptom:
Any balance printed in the page header section that is > abs(999€) will not be matched and results in the last booking entry of the former page losing it's BUCHUNGSINFO in later stages of processing due to unmatched additional chars.

Line 113 of postbank_pdf2csv.sh
Is:
`ZEILE_4='^[ ]+[A-Z]+[ ]+[+-][ ][0-9][0-9,-]+$'`

Solution:
`ZEILE_4='^[ ]+[A-Z]+[ ]+[+-][ ][0-9][0-9,.-]+$'`

I'm not sure why in the last character group minus '-' is matched, thus just left it in there.

**Comment by dukeofnukem815** [comment]
Also switched the whole "LETZTE_ZEILE" context to ERE to fix the broken matching for the end of the input stream

LETZTE_ZEILE='^[[:space:]]+Kontonummer[[:space:]]+BLZ[[:space:]]+Summe Zahlungseingänge[[:space:]]*$'

thus subsequently grep -Ev needs to be used instead of grep -Fv, as well as sed -nre instead of sed -ne when referencing ${LETZTE_ZEILE}

**Comment by FlatheadV8** [comment]
Ich habe die Vorschläge umgesetzt aber nicht getestet!
Da ich diese Skripte seit 2020 nicht mehr verwende (nicht mehr brauche).
Weiterhin funktionierten die bei mir bis dato immer und wenn ein Fehler auftritt, dann benötige ich zur Prüfung immer auch einen Kontoauszug, der diesen Fehler hervorruft.
Genau genommen ist diese Art der Konvertierung ein "dirty hack"...

**Comment by FlatheadV8** [comment]
Gerne kannst Du einen Fork von diesen Skripten anlegen und sie dann selber pflegen... :-)
